[package]
name = "zero_knowledge_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10.8"
ring = "0.16.20"
hex = "0.4.3"
rsa = "0.9.2"
rand = "0.8"
pem = "3.0.2"
thiserror = "1.0.40"